---
- name: Setup Bastion Host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/bastion_setup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{ region }}"
      register: key_out

    - name: private key into bastion
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Bastion Security Group
      ec2_group:
        name: Bastion-host-sg
        description: Allow SSH from trusted IPs and all port SG
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

    - Creating Bastion Host
      ec2:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: Vprofile
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: Vprofile
        group_id: "{{ BastionSG_out.group_id }}"
        vpc_subnet_id: "{{ pubsub1id }}"
      register: bastionHost_out
