---
- name: Setup Bastion Host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/vpc_setup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{ region }}"
      register: key_out

    - name: private key into bastion
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Bastion Security Group
      ec2_group:
        name: Bastion-host-sg
        description: Allow SSH from trusted IPs and all port SG
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

    - name: Creating Bastion Host
      community.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"
        count: 1
        subnet_id: "{{ pubsub1id }}"
        tags:
          - key: Name
            value: Bastion_host
          - key: Project
            value: Vprofile
      register: bastionHost_out

    # Use debug module to inspect the result if needed
    - name: Debug Bastion Host Result
      debug:
        var: bastionHost_out
