---
- name: Setup Bastion Host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/vpc-output_vars

    - name: Import vprofile setup Variables
      include_vars: vprostacksetup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{ region }}"
      register: vprokey_out

    - name: Save private key into file loginkey_vpro.pem
      copy:
        content: "{{ vprokey_out.key.private_key }}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed

    - name: Set ELB Security Group Name
      set_fact:
        elb_sg_name: "your-elb-security-group-name"  # Replace with your actual ELB SG name

    - name: Get ELB Security Group ID
      ec2_group_info:
        name: "{{ elb_sg_name }}"
        region: "{{ region }}"
      register: elb_sg_info

    - set_fact:
        vproELBSG_out: "{{ elb_sg_info.groups[0] }}"

    # Add your other tasks here...

    - name: Ensure SG For vpro stack exists
      ec2_group:
        name: "vproStack-sg"
        description: "Allow port 22 from everywhere and all port within SG"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        purge_rules: yes
        purge_rules_egress: yes
        tags:
          - key: Name
            value: "vproStack-sg"
      register: vproELBSG_out

    # Add more tasks as needed...
